config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  post 'players' => 'players#index'

  get 'register'    => 'players#new'
  post 'register' => 'players#create'

  get 'change_password' => 'players#edit'
  post 'change_password' => 'players#update'

  #get 'change_stats' => 'players#edit2'      #disabled due to riot API implementation, manual changes are no longer required
  #patch 'change_stats' => 'players#update2'  #disabled due to riot API implementation, manual changes are no longer required

  #get 'players/:id/change_stats' => 'players#edit2'
  #post 'players/:id/players/:id/change_stats' => 'players#update2'

  put 'api_update' => 'players#put'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'new_lfg' => 'player_is_lfgs#new'
  post 'new_lfg' => 'player_is_lfgs#create'
  delete "delete_lfg/#{:id}" => 'player_is_lfgs#destroy'

  get 'statistics' => 'static_pages#statistics'

  get 'newteam' => 'teams#new'
  post 'newteam' => 'teams#create'

  post 'team_invites_player' => 'teams#team_invites_player'

  get '/players/get_roles' => 'players#get_roles'

  get 'teams' => 'teams#index'
  post 'teams' => 'teams#index'

  get 'invitations' => 'invites#show'

  post 'invite_accept' => 'invites#accept'
  delete "delete_invitation/#{:id}" => 'invites#destroy'

  resources :players
  resources :player_is_lfgs
  resources :teams
  resources :invites

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  def show
    if current_player.nil?
      redirect_to login_path
      return
    end

    @curr_player = current_player

    @my_posters = PlayerIsLfg.find_by(player_id: @curr_player.id)
    @invitations_into_teams = nil
    unless @my_posters.nil?
      @invitations_into_teams = TeamInvitedPlayer.find_by_sql("SELECT * FROM team_invited_players WHERE player_is_lfg_id = #{@my_posters.id}")
    end

    #this will go into my teams management
    #@my_teams = Team.find_by(id_player: @curr_player.id)
    #@my_invitations = TeamInvitedPlayer.find_by(team_id: @my_teams)
  end

  def accept
    #raise params[:accept_data].inspect

    if current_player.nil?
      redirect_to login_path
      return
    end

    if params[:accept_data].nil?
      redirect_to invitations_path
      return
    end

    parameters = params[:accept_data]

    invitation_id = parameters[:invitation_id]
    invitation = TeamInvitedPlayer.find_by(id: invitation_id)
    if invitation.nil?
      redirect_to invitations_path
      return
    end

    invited_player = Player.find_by(id: parameters[:player_id])
    players_of_team = get_team_members(parameters[:team_id])
    team_roles = get_team_occupied_roles(parameters[:team_id])
    team = Team.find_by(id: parameters[:team_id])

    if current_player.id.to_i == invited_player.id.to_i

      @isValidMi = 1
      #Check if to be invited player is not already member of team
      players_of_team.each do |pot|
        if pot.id.to_i == invited_player.id.to_i
          @isValidMi = 0
          break
        end
      end

      @isValidTRi = 1
      #Check if role that to be invited player wants to play isn't already occupied in team roster
      team_roles.each do |tr|
        if tr.id.to_i == parameters[:concrete_role_id].to_i
          @isValidTRi = 0
        end
      end

      @isValidRei = 0
      #Check if player is from same region as is team
      if invited_player.region_id.to_i == team.id_region.to_i
        @isValidRei = 1
      end

      if (@isValidMi == 1 && @isValidTRi == 1 && @isValidTRi == 1)
        membership = PlayerTeam.new
        membership.player_id = parameters[:player_id]
        membership.team_id = parameters[:team_id]
        membership.concrete_role_id = parameters[:concrete_role_id]
        membership.created_at = Time.now
        membership.updated_at = Time.now

        team_role_list_id = team.id_role_list
        team_add_role_id = parameters[:concrete_role_id]

        new_role = Role.new
        new_role.role_list_id = team_role_list_id
        new_role.concrete_role_id = team_add_role_id

        #ActiveRecord::Base.transaction do
          ActiveRecord::Base.connection.execute(
              "DELETE FROM team_invited_players WHERE id=#{invitation_id};"
          )
          membership.save
          new_role.save
        #end

        redirect_to team
      end
    end
  end

  def destroy
    if current_player.nil?
      redirect_to login_path
      return
    end

    invitation_id = params[:format]
    invitation = TeamInvitedPlayer.find_by(id: invitation_id)
    if invitation.nil?
      redirect_to invitations_path
      return
    end
    invited_players_lfg = PlayerIsLfg.find_by(id: invitation.player_is_lfg_id)
    invited_player = Player.find_by(id: invited_players_lfg.player_id)
    if current_player.id.to_i == invited_player.id.to_i
      ActiveRecord::Base.connection.execute(
          "DELETE FROM team_invited_players WHERE id=#{invitation_id};"
      )
    end
    redirect_to invitations_path
  end

end

app/views/invites/accept.html.erb
<% provide(:title,"Accept error") %>
<br><br>
<div class="container">
  <% if @isValidMi == 0 %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <ul>
          <li>You are already member of this team.</li>
        </ul>
      </div>
    </div>
  <% end %>
  <% if @isValidTRi == 0 %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <ul>
          <li>Player with your role was already found.</li>
        </ul>
      </div>
    </div>
  <% end %>
  <% if @isValidTRi == 0 %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <ul>
          <li>Team plays in another region.</li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/invites/show.html.erb
<% provide(:title, "Invitations") %>

<div class="container">
  <h1>Invitations</h1>
  <% if @invitations_into_teams.nil? %>
      <p>You have no invitations.</p>
  <% else %>

  <table class="table table-condensed">
    <thead>
    <tr>
      <th>Team</th>
      <th>Role</th>
      <th>&nbsp</th>
      <th>&nbsp</th>
    </tr>
    </thead>
    <tbody>
    <% @invitations_into_teams.each do |invitation| %>
      <tr>
        <% temp_team = Team.find_by(id: invitation.team_id) %>
        <td><span class="white-link"><%= link_to temp_team.name, temp_team  %></span></td>
        <td><%= get_concrete_role_by_id(invitation.concrete_role_id).name %></td>
        <% lfg_temp = get_player_is_lfg_by_team_invited_player_id(invitation.player_is_lfg_id) %>
        <% player_temp = get_player_by_lfg_id(lfg_temp.player_id) %>
        <% if !current_player.nil? && player_temp.id == current_player.id %>
          <%= form_for(:accept_data, url: '/invite_accept') do |f| %>
            <%= f.hidden_field :team_id, value: "#{temp_team.id}" %>
            <%= f.hidden_field :player_id, value: "#{player_temp.id}" %>
            <%= f.hidden_field :concrete_role_id, value: "#{invitation.concrete_role_id}" %>
            <%= f.hidden_field :invitation_id, value: "#{invitation.id}" %>
            <td><%= f.submit "Accept", class: "clear-button-green" %></td>
          <% end %>
        <% end %>
        <% if !current_player.nil? && player_temp.id == current_player.id %>
          <td><span class="red-link"><%= link_to "Reject", delete_invitation_id_path(invitation.id), method: :delete %></span></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
  <% end %>
</div>