config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  post 'players' => 'players#index'

  get 'register'    => 'players#new'
  post 'register' => 'players#create'

  get 'change_password' => 'players#edit'
  post 'change_password' => 'players#update'

  #get 'change_stats' => 'players#edit2'      #disabled due to riot API implementation, manual changes are no longer required
  #patch 'change_stats' => 'players#update2'  #disabled due to riot API implementation, manual changes are no longer required

  #get 'players/:id/change_stats' => 'players#edit2'
  #post 'players/:id/players/:id/change_stats' => 'players#update2'

  put 'api_update' => 'players#put'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'new_lfg' => 'player_is_lfgs#new'
  post 'new_lfg' => 'player_is_lfgs#create'
  delete "delete_lfg/#{:id}" => 'player_is_lfgs#destroy'

  get 'statistics' => 'static_pages#statistics'

  get 'newteam' => 'teams#new'
  post 'newteam' => 'teams#create'

  post 'team_invites_player' => 'teams#team_invites_player'

  get '/players/get_roles' => 'players#get_roles'

  get 'teams' => 'teams#index'
  post 'teams' => 'teams#index'

  get 'invitations' => 'invites#show'

  post 'invite_accept' => 'invites#accept'
  delete "delete_invitation/#{:id}" => 'invites#destroy'

  resources :players
  resources :player_is_lfgs
  resources :teams
  resources :invites

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :concrete_league
  has_many :region
  belongs_to :player_requested_membership_in_team
  belongs_to :player_team
  belongs_to :team
  belongs_to :player_is_lfg

  attr_accessor :remember_token

  validates :login, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 50 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :name, presence: true

  validates :name, uniqueness: { scope: :region_id }


  def Player.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def Player.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = Player.new_token
    update_attribute(:remember_digest, Player.digest(remember_token))
  end

  def authenticated?(remember_token)
    if remember_digest.nil?
      false
    else
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/players_controller.rb
require 'net/http'
require 'json'


class PlayersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :edit2, :update]

  def new
    @player = Player.new
  end

  def index
    #@players = Player.paginate(page: params[:page])
    #@player_is_lfgs = PlayerIsLfg.all
    @player_is_lfgs = PlayerIsLfg.find_by_sql("SELECT * FROM player_is_lfgs")

    if params[:search_lfg]
      parameters = params[:search_lfg]
      @minimal_league_rating = ConcreteLeague.find_by(id: parameters[:minimal_league_id]).rating
      @maximal_league_rating = ConcreteLeague.find_by(id: parameters[:maximal_league_id]).rating
      if (parameters[:top] == '1' || parameters[:jungle] == '1' || parameters[:mid] == '1' || parameters[:support] == '1' || parameters[:bot] == '1') && ( @minimal_league_rating.to_i <= @maximal_league_rating.to_i )
        conditions = []
        if parameters[:top] == '1'
          conditions << "cr.name = 'Top'"
        end
        if parameters[:jungle] == '1'
          conditions <<  "cr.name = 'Jungle'"
        end
        if parameters[:mid] == '1'
          conditions <<  "cr.name = 'Mid'"
        end
        if parameters[:support] == '1'
          conditions <<  "cr.name = 'Support'"
        end
        if parameters[:bot] == '1'
          conditions <<  "cr.name = 'Bot'"
        end
        where_str = "WHERE (#{conditions.join(" OR ")}) AND cl.rating >= #{@minimal_league_rating} AND cl.rating <= #{@maximal_league_rating}"

        sql_str = 'SELECT DISTINCT lfg.* FROM player_is_lfgs lfg
                      JOIN role_lists rl ON lfg.role_list_id=rl.id
                      JOIN roles r ON r.role_list_id=rl.id
                      JOIN concrete_roles cr ON r.concrete_role_id=cr.id
                      JOIN players p ON lfg.player_id=p.id
                      JOIN concrete_leagues cl ON p.concrete_league_id=cl.id ' + where_str

        @player_is_lfgs = PlayerIsLfg.find_by_sql(sql_str)
      end
    end
  end

  def show
    @player = Player.find_by_sql("SELECT * FROM players WHERE id=#{params[:id]} LIMIT 1")[0]
    if @player.nil?
      redirect_to players_path
    else
      session[:viewed_player_id] = @player.id

      @ar = ActiveRecord::Base.connection.execute(
          "SELECT p.id, COUNT(lfg.id) as c FROM players p
          JOIN player_is_lfgs lfg ON lfg.player_id = p.id
          WHERE p.id=#{@player.id}
          GROUP BY p.id;"
      )

      @player_is_lfgs = PlayerIsLfg.find_by_sql("SELECT * FROM player_is_lfgs p WHERE player_id=#{@player.id};")
    end
  end

  def create
    @player = Player.new(params.require(:player).permit(:name, :login, :password, :password_confirmation, :region_id))
    parameters = params[:player]
    if @player.valid?
      region = Region.find_by(id: parameters[:region_id])
      uri = URI.parse("https://#{region.short}.api.pvp.net/api/lol/#{region.short}/v1.4/summoner/by-name/#{parameters[:name]}?api_key=#{ENV['riot_api_key']}")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      request = Net::HTTP::Get.new(uri.request_uri)
      response = http.request(request)
      parsed = JSON.parse(response.body)

      if(parsed["status"].nil?)
        #raise "actuall data"
        sql_in_name = ActiveRecord::Base.sanitize parameters[:name]
        sql_in_login = ActiveRecord::Base.sanitize parameters[:login]
        sql_in_region_id = ActiveRecord::Base.sanitize parameters[:region_id]
        sql_in_password_digest = Player.digest parameters[:password]
        sql_in_riot_summoner_id = parsed[parameters[:name].downcase]["id"]
        ActiveRecord::Base.connection.execute("INSERT INTO players (name,login,region_id,concrete_league_id,win,lose,password_digest,created_at,updated_at,riot_summoner_id) VALUES (#{sql_in_name},#{sql_in_login},#{sql_in_region_id},1,0,0,'#{sql_in_password_digest}',timestamptz '#{Time.now}',timestamptz '#{Time.now}',#{sql_in_riot_summoner_id});")
        pp = Player.find_by(login: parameters[:login])
        log_in pp
        #$redis.zincrby("playersByLeague",1,"[\"1\",\"Unranked\"]")
        #flash[:success] = 'Welcome'
        redirect_to pp
      else
        if(parsed["status"]["status_code"] == 404)
          @not_found_error = 1
        elsif(parsed["status"]["status_code"] == 429)
          @overload_error = 1
        else
          @unknown_error = 1
        end
        render 'new'
      end
    else
      render 'new'
    end
  end

  def edit
    @player = Player.find_by_sql("SELECT * FROM players WHERE id=#{current_player.id} LIMIT 1")[0]
  end

  def update
    @player = Player.find_by_sql("SELECT * FROM players WHERE id=#{current_player.id} LIMIT 1")[0]

    parameters = params[:player_data]

    @error_wrong_confirm = 0
    @error_wrong_pass = 0
    if @player && @player.authenticate(parameters[:password_old])
      if parameters[:password] == parameters[:password_confirmation]
        sql_in_password_digest = Player.digest parameters[:password]
        ActiveRecord::Base.connection.execute("UPDATE players SET password_digest = '#{sql_in_password_digest}', updated_at = timestamptz '#{Time.now}' WHERE id = #{@player.id};")
        redirect_to @player
        return
      else
        @error_wrong_confirm = 1
      end
    else
      @error_wrong_pass = 1
    end
    render 'edit'

    # if @player.update_attributes(player_params)
    #   redirect_to @player
    # else
    #   render 'edit'
    # end
  end

  def edit2
    @player = Player.find_by_sql("SELECT * FROM players WHERE id=#{current_player.id} LIMIT 1")[0]
  end

  def update2
    @player = Player.find_by_sql("SELECT * FROM players WHERE id=#{current_player.id} LIMIT 1")[0]
    parameters = params[:player]
    div = ConcreteLeague.find_by(id: current_player.concrete_league_id)[:division]
    member = JSON.generate([current_player.concrete_league_id.to_s, div])
    $redis.zincrby('playersByLeague',-1,member)
    ActiveRecord::Base.connection.execute("UPDATE players SET concrete_league_id = #{parameters[:concrete_league_id]}, win = #{parameters[:win]}, lose = #{parameters[:lose]}, updated_at = timestamptz '#{Time.now}' WHERE id = #{@player.id};")
    div = ConcreteLeague.find_by(id: parameters[:concrete_league_id])[:division]
    member = JSON.generate([parameters[:concrete_league_id], div])
    $redis.zincrby('playersByLeague',1,member)
    redirect_to @player
  end

  def put
    if session[:viewed_player_id].nil?
    else
      @player = Player.find_by_sql("SELECT * FROM players WHERE id=#{ session[:viewed_player_id] } LIMIT 1")[0]
      session.delete(:viewed_player_id)

      region = Region.find_by(id: @player.region_id)
      uri = URI.parse("https://#{region.short}.api.pvp.net/api/lol/#{region.short}/v2.5/league/by-summoner/#{@player.riot_summoner_id}/entry/?api_key=#{ENV['riot_api_key']}")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE

      request = Net::HTTP::Get.new(uri.request_uri)

      response = http.request(request)
      parsed = JSON.parse(response.body)


      if parsed["status"].nil?
        #raise "actuall data"
        #raise parsed[@player.riot_summoner_id.to_s].inspect
        player_data_all = parsed[@player.riot_summoner_id.to_s]
        player_data = nil
        player_data_all.each do |queue|
          if queue["queue"].eql? "RANKED_SOLO_5x5"
            player_data = queue
            break
          end
        end


        unless player_data.nil?
          default_entry = player_data["entries"][0]
          tier = player_data["tier"]
          division = default_entry["division"]
          league_points = default_entry["leaguePoints"]
          wins = default_entry["wins"]
          losses = default_entry["losses"]

          if tier.eql? "Challenger" || tier.eql? == "Master"
            div_name = "#{tier}"
          elsif
          div_name = "#{tier} #{division}"
          end

          div_id = ConcreteLeague.find_by_sql("SELECT * FROM concrete_leagues WHERE lower(division) LIKE '#{div_name.underscore}' LIMIT 1")[0][:id]

          # redis
          # div = ConcreteLeague.find_by(id: current_player.concrete_league_id)[:division]
          # member = JSON.generate([current_player.concrete_league_id.to_s, div])
          # $redis.zincrby('playersByLeague',-1,member)
          # div = ConcreteLeague.find_by(id: div_id)[:division]
          # member = JSON.generate([:div_id, div])
          # $redis.zincrby('playersByLeague',1,member)

          ActiveRecord::Base.connection.execute("UPDATE players SET concrete_league_id = #{div_id}, win = #{wins}, lose = #{losses}, league_points = #{league_points},updated_at = timestamptz '#{Time.now}' WHERE id = #{@player.id};")
        end
      else
        if(parsed["status"]["status_code"] == 404)
          @not_found_error = 1
        elsif(parsed["status"]["status_code"] == 429)
          @overload_error = 1
        else
          @unknown_error = 1
        end
      end
    end

    redirect_to @player
  end

  def get_roles
    player_lfg_id = params[:player_lfg_id]

    @roles = get_player_lfgs_roles(player_lfg_id)

    render layout: false
  end

  private

    def player_params
      params.require(:player).permit(:password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

end

app/helpers/players_helper.rb
module PlayersHelper

  def get_roles(role_list_id)
    role_list = ConcreteRole.find_by_sql(
        "SELECT cr.* FROM concrete_roles cr
        JOIN roles r ON r.concrete_role_id = cr.id
        WHERE r.role_list_id = #{role_list_id}"
    )
  end

  def teams_of_which_current_player_is_captain
    if current_player.nil?
      return nil
    else
      @teams = Team.find_by(id_player: current_player.id)
    end
  end

end

app/views/players/_error_password_change.html.erb
<% if(@error_wrong_confirm == 1 || @error_wrong_pass == 1) %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <ul>
          <% if(@error_wrong_confirm == 1) %>
              <li>Wrong confirmation password</li>
              <% @error_wrong_confirm = 0 %>
          <% end %>
          <% if(@error_wrong_pass == 1) %>
              <li>Wrong old password</li>
              <% @error_wrong_pass = 0 %>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/players/_form_error.html.erb
<div id="error_explanation">
  <div class="alert alert-danger">
    <ul>
      <li>Chose at least one role</li>
    </ul>
  </div>
</div>

app/views/players/_league_range_error.html.erb
<div id="error_explanation">
  <div class="alert alert-danger">
    <ul>
      <li>Minimum league must be lower then maximum league</li>
    </ul>
  </div>
</div>

app/views/players/_server_overloaded.html.erb
<% if(@overload_error == 1 || @not_found_error == 1 || @unknown_error == 1) %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <ul>
        <% if(@overload_error == 1) %>
            <li>Server overloaded, try again later.</li>
            <% @overload_error = 0 %>
        <% end %>
        <% if(@not_found_error == 1) %>
            <li>Summoner not found, please check your ingame nickname.</li>
            <% @not_found_error = 0 %>
        <% end %>
        <% if(@unknown_error == 1) %>
            <li>Unknown error has occurred.</li>
            <% @unknown_error = 0 %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/players/edit.html.erb
<% provide(:title, "Change password") %>

<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(:player_data, url:'/change_password') do |f| %>
        <%= render 'shared/error_messages' %>
        <%= render 'players/error_password_change' %>

        <%= f.label :old_password %>
        <%= f.password_field :password_old, class: 'form-control' %>

        <%= f.label :new_password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/players/edit2.html.erb
<% provide(:title, "Edit profile") %>

<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@player, url: change_stats_path) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :league %>
        <div class="divider"></div>
        <span style="color:black"><%= f.select :concrete_league_id, options_from_collection_for_select(ConcreteLeague.all, :id, :division), class: 'form-control' %></span>
        <div class="divider"></div>

        <div class="col-md-6">
          <%= f.label :win %>
          <%= f.number_field :win, :required => 'required', class: 'form-control' %>
        </div>

        <div class="col-md-6">
          <%= f.label :lose %>
          <%= f.number_field :lose, :required => 'required', class: 'form-control' %>
        </div>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/players/get_roles.html.erb
<% @roles.each do |role| %>
  <option value="<%= role.id %>"><%= role.name %></option>
<% end %>

app/views/players/index.html.erb
<% provide(:title, 'Players') %>
<div class="row">
  <div class="left-nav-lfg">
    <%= form_for(:search_lfg, url: '/players') do |f| %>
      <br><h1>League</h1>
      <br><h2 style="margin-bottom: 10px;">Minimum</h2>
      <br><div class="col-md-8 col-md-offset-2" style="color: black;"><%= f.select :minimal_league_id, options_from_collection_for_select(ConcreteLeague.all, :id, :division), class: 'form-control' %></div>
      <br><br><h2 style="margin-bottom: 10px;">Maximum</h2>
      <br><div class="col-md-8 col-md-offset-2" style="color: black;"><%= f.select :maximal_league_id, options_from_collection_for_select(ConcreteLeague.all, :id, :division), class: 'form-control' %></div>

      <br><br><h2 style="margin-bottom: 10px;">Roles</h2>
      <div class="divider" style="margin: 10px;"></div>
      <br>
      <div class="col-md-8 col-md-offset-2">
        <%= f.label :top, class: "checkbox inline" do %>
            <div class="col-md-8">Top</div>
            <div class="col-md-4"><%= f.check_box :top %></div>
        <% end %>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <%= f.label :jungle, class: "checkbox inline" do %>
            <div class="col-md-8">Jungle</div>
            <div class="col-md-4"><%= f.check_box :jungle %></div>
        <% end %>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <%= f.label :mid, class: "checkbox inline" do %>
            <div class="col-md-8">Mid</div>
            <div class="col-md-4"><%= f.check_box :mid %></div>
        <% end %>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <%= f.label :support, class: "checkbox inline" do %>
            <div class="col-md-8">Support</div>
            <div class="col-md-4"><%= f.check_box :support %></div>
        <% end %>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <%= f.label :bot, class: "checkbox inline" do %>
            <div class="col-md-8">Bot</div>
            <div class="col-md-4"><%= f.check_box :bot %></div>
        <% end %>
      </div>

      <div class="col-md-8 col-md-offset-2">
        <%= f.submit "Filter", class: "btn btn-primary" %>
      </div>
    <% end %>
    <div style="clear:both;"></div>
    <div style="height: 75px;"></div>
    <% parameters = params[:search_lfg] %>
    <% if params[:search_lfg] %>
      <% if !(parameters[:top] == '1' || parameters[:jungle] == '1' || parameters[:mid] == '1' || parameters[:support] == '1' || parameters[:bot] == '1') %>
        <%= render 'players/form_error' %>
        <% @stop = 1 %>
      <% end %>
      <% if @minimal_league_rating.to_i > @maximal_league_rating.to_i %>
        <%= render 'players/league_range_error' %>
        <% @stop = 1 %>
      <% end %>
    <% end %>
  </div>

  <div style="padding-left: 350px;">
    <div class="container">
      <% @player_is_lfgs.each do |player_is_lfg| %>
        <div class="poster">
          <%
            @player = Player.find_by(id: player_is_lfg.player_id)
            @cl = ConcreteLeague.find_by(id: @player.concrete_league_id)
          %>
          <div class="division"><%=
            @cl.division
          %></div>
          <div class="divider"></div>
          <%=
            image_tag("league_badges/#{@cl.img}.png", alt: "#{@cl.division}")
          %>
          <div class="divider"></div>
          <div class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <div class="player-name"><%= @player.name %></div>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", @player %></li>
              <% unless current_player.nil? %>
                <% if teams_of_which_current_player_is_captain.nil? %>
                  <li><%= link_to "Invite to team", "#", :onclick => "show('invite-player')" %></li>
                <% else %>
                  <li><%= link_to "Invite to team", "#", :onclick => "get_roles(#{player_is_lfg.id})" %></li> <!-- show('invite-player')          -->
                <% end %>
              <% end %>
            </ul>
          </div>

          <div class="popup" id="invite-player" <% if teams_of_which_current_player_is_captain.nil? %>style="height: 170px;"<% end %>>
            <% if teams_of_which_current_player_is_captain.nil? %>
              <p>You are not captain of any eligible team!</p>
              <%= link_to "Create team", newteam_path, class: "btn btn-primary col-md-4 col-md-offset-1", style:"color: white;" %>
            <% else %>
              <%= form_for(:invite_data, url: '/team_invites_player') do |f| %>
                <%= f.label :select_team %>
                <span style="color:black; font-size: 16px;"><%= f.select :team_id, options_from_collection_for_select(Team.where(id_player: current_player.id), :id, :name), class: 'form-control' %></span>

                <%= f.label :select_position %>
                <span style="color:black; font-size: 16px;" id="role-select-id"><%= f.select :concrete_role_id, options_from_collection_for_select(ConcreteRole.all, :id, :name), id: 'roleselectid' , class: 'form-control' %></span> <!-- get_player_lfgs_roles(@player.id) -->

                <%= f.label :message %>
                <%= f.text_area :note, placeholder: 'Maximum 500 characters', class: 'form-control' %>

                <%= f.hidden_field :player_lfg_id, value: '' %>

                <%= f.submit "Invite", class: "btn btn-primary col-md-4 col-md-offset-1" %>
              <% end %>
            <% end %>
            <a href="#" class="btn btn-primary col-md-4 col-md-offset-2" style="color: white;" onclick="hide('invite-player')">Cancel</a>
          </div>

          <div class="divider"></div>
          <p><span class="win"><%= @player.win %> W</span> / <span class="lose"><%= @player.lose %> L</span></p>
          <div class="divider"></div>
          <%
            role_list = get_roles(player_is_lfg.role_list_id)
          %>
          <% role_list.each do |role| %>
              <%= image_tag("role_badges/#{role[:name].downcase}.png", :width => 36, :height => 36, alt: "role_badges/#{role[:name]}.png") %>
          <% end %>
          <div class="divider"></div>
          <p style="margin-top:15px;">League range</p>
          <div class="league-range">
            <p style="margin: 0px">From: <%= ConcreteLeague.find_by(id: player_is_lfg.concrete_league_id_min).division %></p>
            <p style="margin: 0px">To: <%= ConcreteLeague.find_by(id: player_is_lfg.concrete_league_id_max).division %></p>
            <p style="margin: 0px">Region: <%= Region.find_by(id: @player.region_id).name %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>





<div style="clear:both;"></div>

app/views/players/new.html.erb
<% provide(:title,"Registration") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@player, url: '/register') do |f| %>
        <%= render 'shared/error_messages' %>
        <%= render 'players/server_overloaded' %>

        <%= f.label :summoner_name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :login %>
        <%= f.text_field :login, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.label :region %>
        <span style="color:black"><%= f.select :region_id, options_from_collection_for_select(Region.all, :id, :name), class: 'form-control' %></span>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/players/show.html.erb
<% provide(:title, @player.name) %>
<div class="container">
  <h3>
    <%= @player.name %>
  </h3>

  <%
    @cl = ConcreteLeague.find_by(id: @player.concrete_league_id)
  %>
  <p>League: <%= @cl.division %>   <%= image_tag("league_badges/#{@cl.img}.png", alt: "#{@cl.division}", :width => 40, :height => 40) %></p>
  <p>Region: <%= Region.find_by(id: @player.region_id).name %></p>
  <p>Wins: <span style="color: darkgreen"><%= @player.win %> W</span></p>
  <p>Loses: <span style="color: darkred"><%= @player.lose %> L</span></p>
  <% if @ar.to_a.length == 0 %>
    <p>Number of posters: 0</p>
  <% else %>
    <p>Number of posters: <%= @ar[0]["c"] %></p>
  <% end %>

  <% if !current_player.nil? && current_player.id == @player.id %>
    <%= link_to "Create poster", new_lfg_path, method: :get, class: "btn btn-primary" %>
    <%= link_to "Renew", api_update_path, method: :put, class: "btn btn-primary" %>
  <% end %>


  <% if @ar.to_a.length > 0 %>
    <div class="divider"></div>
    <span style="margin: 20px;"><p>Posters:</p></span>
    <div class="player-poster-table col-md-8">

      <div class="row">
        <div class="col-md-3">Minimum league</div>
        <div class="col-md-3">Maximum league</div>
        <div class="col-md-5">Roles</div>
      </div>
      <% @player_is_lfgs.each do |poster| %>
          <% poster_id = poster.id %>
          <div class="row">
            <div class="col-md-3"><%= ConcreteLeague.find_by(id: poster.concrete_league_id_min).division %></div>
            <div class="col-md-3"><%= ConcreteLeague.find_by(id: poster.concrete_league_id_max).division %></div>
            <div class="col-md-5">
              <%
                role_list = get_roles(poster.role_list_id)
              %>
              <% role_list.each do |role| %>
                  <%= image_tag("role_badges/#{role[:name].downcase}.png", :width => 20, :height => 20, alt: "#{role[:name]}") %>
              <% end %>
            </div>
            <% if !current_player.nil? && @player.id == current_player.id %>
              <div class="col-md-1" style="font-family: 'Arial'"><%= link_to "X", delete_lfg_id_path(poster_id), method: :delete%></div>
            <% end %>
          </div>
          <div class="divider"></div>
    <% end %>
    </div>
  <% end %>
</div>