config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  post 'players' => 'players#index'

  get 'register'    => 'players#new'
  post 'register' => 'players#create'

  get 'change_password' => 'players#edit'
  post 'change_password' => 'players#update'

  #get 'change_stats' => 'players#edit2'      #disabled due to riot API implementation, manual changes are no longer required
  #patch 'change_stats' => 'players#update2'  #disabled due to riot API implementation, manual changes are no longer required

  #get 'players/:id/change_stats' => 'players#edit2'
  #post 'players/:id/players/:id/change_stats' => 'players#update2'

  put 'api_update' => 'players#put'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'new_lfg' => 'player_is_lfgs#new'
  post 'new_lfg' => 'player_is_lfgs#create'
  delete "delete_lfg/#{:id}" => 'player_is_lfgs#destroy'

  get 'statistics' => 'static_pages#statistics'

  get 'newteam' => 'teams#new'
  post 'newteam' => 'teams#create'

  post 'team_invites_player' => 'teams#team_invites_player'

  get '/players/get_roles' => 'players#get_roles'

  get 'teams' => 'teams#index'
  post 'teams' => 'teams#index'

  get 'invitations' => 'invites#show'

  post 'invite_accept' => 'invites#accept'
  delete "delete_invitation/#{:id}" => 'invites#destroy'

  resources :players
  resources :player_is_lfgs
  resources :teams
  resources :invites

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Play <a href="http://www.leagueoflegends.com/">League of Legends</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Link 1", "#" %></li>
      <li><%= link_to "Link 2", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <%= link_to "players", players_path, class:"custom-top-left-nav" %>
    <%= link_to "teams", teams_path , class:"custom-top-left-nav" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if current_player.nil? %>
          <li><%= link_to "Register", register_path %></li>
        <% end %>
        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_player %></li>
                <li><%= link_to "Invitations", invitations_path, :'data-no-turbolink' => "true" %></li>
                <li><%= link_to "Create team", newteam_path  %></li>
                <li><%= link_to "Change password", change_password_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <div class="container">
      <%#= render 'layouts/footer' %>
       <!--debug(params) if Rails.env.development?-->
    </div>
  </body>
</html>